export type PassportCountry =
  | 'KR'
  | 'US'
  | 'JP'
  | 'GB'
  | 'DE'
  | 'FR'
  | 'ES'
  | 'IT'
  | 'CA'
  | 'AU'
  | 'NZ'
  | 'SG'
  | 'CN'
  | 'IN'
  | 'OTHER';

export type VisaType =
  | 'tourist'
  | 'business'
  | 'student'
  | 'work'
  | 'transit'
  | 'digital-nomad'
  | 'investor'
  | 'working-holiday'
  | 'spouse'
  | 'medical';

export interface VisaRequirement {
  visaRequired: boolean;
  visaType: 'visa-free' | 'visa-on-arrival' | 'evisa' | 'embassy';
  processingTime: string;
  fee: string;
  maxStay: string;
  notes?: string;
  validityPeriod?: string;
  multipleEntry?: boolean;
}

export interface EmbassyInfo {
  address: string;
  phone?: string;
  email?: string;
  website?: string;
  workingHours?: string;
}

export interface CountryData {
  name: string;
  region: string;
  capital?: string;
  currency?: string;
  timezone?: string;
  language?: string[];
  requirements: Record<PassportCountry, VisaRequirement>;
  visaTypes: VisaType[];
  requiredDocuments: string[];
  embassy?: EmbassyInfo;
  travelAdvisory: 'low' | 'medium' | 'high';
  covidRequirements?: string[];
  popularDestinations?: boolean;
}

export const _PASSPORT_COUNTRIES = [
  { code: 'KR' as const, name: 'South Korea', flag: '🇰🇷' },
  { code: 'US' as const, name: 'United States', flag: '🇺🇸' },
  { code: 'JP' as const, name: 'Japan', flag: '🇯🇵' },
  { code: 'GB' as const, name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'DE' as const, name: 'Germany', flag: '🇩🇪' },
  { code: 'FR' as const, name: 'France', flag: '🇫🇷' },
  { code: 'ES' as const, name: 'Spain', flag: '🇪🇸' },
  { code: 'IT' as const, name: 'Italy', flag: '🇮🇹' },
  { code: 'CA' as const, name: 'Canada', flag: '🇨🇦' },
  { code: 'AU' as const, name: 'Australia', flag: '🇦🇺' },
  { code: 'NZ' as const, name: 'New Zealand', flag: '🇳🇿' },
  { code: 'SG' as const, name: 'Singapore', flag: '🇸🇬' },
  { code: 'CN' as const, name: 'China', flag: '🇨🇳' },
  { code: 'IN' as const, name: 'India', flag: '🇮🇳' },
  { code: 'OTHER' as const, name: 'Other', flag: '🌍' },
];

export const VISA_DATABASE: Record<string, CountryData> = {
  // Europe - Schengen Countries
  FR: {
    name: 'France',
    region: 'Western Europe',
    capital: 'Paris',
    currency: 'EUR',
    timezone: 'CET/CEST',
    language: ['French'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '5-10 days',
        fee: '€60',
        maxStay: '30 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '7-15 days',
        fee: '€80',
        maxStay: '30 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '10-15 days',
        fee: '€80',
        maxStay: '30 days',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit'],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'Proof of accommodation',
      'Return ticket',
      'Proof of sufficient funds (€65/day)',
      'Travel insurance (€30,000 coverage)',
    ],
    embassy: {
      address: '서울특별시 서초구 서초대로 2157 (서초동)',
      phone: '+82-2-3149-4300',
      website: 'https://kr.ambafrance.org',
      workingHours: '09:00-12:00 (Mon-Fri)',
    },
  },

  DE: {
    name: 'Germany',
    region: 'Central Europe',
    capital: 'Berlin',
    currency: 'EUR',
    timezone: 'CET/CEST',
    language: ['German'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '5-10 days',
        fee: '€75',
        maxStay: '90 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '7-15 days',
        fee: '€75',
        maxStay: '90 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '10-15 days',
        fee: '€75',
        maxStay: '90 days',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit'],
    requiredDocuments: [
      'Valid passport (3+ months validity)',
      'Completed application form',
      'Passport photos',
      'Travel itinerary',
      'Proof of accommodation',
      'Financial proof',
      'Travel insurance',
    ],
    embassy: {
      address: '서울특별시 중구 명동길 7, 명동센터빌딩 17층',
      phone: '+82-2-748-4114',
      website: 'https://seoul.diplo.de',
      workingHours: '08:30-11:30 (Mon-Fri)',
    },
  },

  ES: {
    name: 'Spain',
    region: 'Southern Europe',
    capital: 'Madrid',
    currency: 'EUR',
    timezone: 'CET/CEST',
    language: ['Spanish'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '7-10 days',
        fee: '€60',
        maxStay: '90 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '10-15 days',
        fee: '€60',
        maxStay: '90 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '10-15 days',
        fee: '€60',
        maxStay: '90 days',
      },
    },
    visaTypes: [
      'tourist',
      'business',
      'student',
      'work',
      'transit',
      'digital-nomad',
    ],
    requiredDocuments: [
      'Valid passport (3+ months validity)',
      'Visa application form',
      'Recent passport photo',
      'Travel insurance (€30,000)',
      'Flight reservations',
      'Hotel reservations or invitation letter',
      'Bank statements (3 months)',
    ],
    embassy: {
      address: '서울특별시 종로구 종로1길 50, 더케이트윈타워 A동 23층',
      phone: '+82-2-397-3703',
      website: 'https://www.exteriores.gob.es/Embajadas/seul',
      workingHours: '09:00-13:00 (Mon-Fri)',
    },
  },

  IT: {
    name: 'Italy',
    region: 'Southern Europe',
    capital: 'Rome',
    currency: 'EUR',
    timezone: 'CET/CEST',
    language: ['Italian'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days (180-day period)',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '7-10 days',
        fee: '€35',
        maxStay: '90 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '10-15 days',
        fee: '€35',
        maxStay: '90 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '10-15 days',
        fee: '€35',
        maxStay: '90 days',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit'],
    requiredDocuments: [
      'Valid passport (3+ months validity)',
      'Completed visa application',
      'Recent passport photos',
      'Travel insurance',
      'Flight bookings',
      'Accommodation proof',
      'Financial means proof',
    ],
    embassy: {
      address: '서울특별시 중구 정동길 15',
      phone: '+82-2-796-0491',
      website: 'https://ambseoul.esteri.it',
      workingHours: '09:00-12:00 (Mon-Fri)',
    },
  },

  // Americas
  US: {
    name: 'United States',
    region: 'North America',
    capital: 'Washington, D.C.',
    currency: 'USD',
    timezone: 'Multiple',
    language: ['English'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
        notes: 'ESTA authorization required',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: 'N/A',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'ESTA required',
        fee: '$21 (ESTA)',
        maxStay: '90 days',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '3-5 days',
        fee: '$160',
        maxStay: '10 years (multiple entry)',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '3-5 days',
        fee: '$160',
        maxStay: '10 years (multiple entry)',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '3-5 days',
        fee: '$160',
        maxStay: 'Varies',
      },
    },
    visaTypes: [
      'tourist',
      'business',
      'student',
      'work',
      'transit',
      'investor',
    ],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'DS-160 form',
      'Passport photo',
      'Visa fee payment receipt',
      'Supporting documents (varies by visa type)',
      'Interview appointment (most cases)',
    ],
    embassy: {
      address: '서울특별시 중구 세종대로 188',
      phone: '+82-2-397-4114',
      website: 'https://kr.usembassy.gov',
      workingHours: '08:00-17:00 (Mon-Fri)',
    },
  },

  CA: {
    name: 'Canada',
    region: 'North America',
    capital: 'Ottawa',
    currency: 'CAD',
    timezone: 'Multiple',
    language: ['English', 'French'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
        notes: 'Electronic Travel Authorization required',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'eTA required',
        fee: 'CAD $7 (eTA)',
        maxStay: '6 months',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '20 days',
        fee: 'CAD $100',
        maxStay: '6 months',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '20 days',
        fee: 'CAD $100',
        maxStay: '6 months',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '20 days',
        fee: 'CAD $100',
        maxStay: '6 months',
      },
    },
    visaTypes: [
      'tourist',
      'business',
      'student',
      'work',
      'transit',
      'working-holiday',
    ],
    requiredDocuments: [
      'Valid passport',
      'Completed application form',
      'Photos',
      'Proof of support',
      'Purpose of visit documents',
      'Medical exam (if required)',
      'Police certificates (if required)',
    ],
    embassy: {
      address: '서울특별시 중구 정동길 21-15 덕수궁길 15',
      phone: '+82-2-3783-6000',
      website: 'https://www.canada.ca/en/immigration-refugees-citizenship',
      workingHours: '08:30-12:00, 13:00-16:30 (Mon-Fri)',
    },
  },

  // Asia-Pacific
  JP: {
    name: 'Japan',
    region: 'East Asia',
    capital: 'Tokyo',
    currency: 'JPY',
    timezone: 'JST',
    language: ['Japanese'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: 'N/A',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-6 days',
        fee: '¥3,000',
        maxStay: '15-90 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-6 days',
        fee: '¥3,000',
        maxStay: '15-90 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-6 days',
        fee: '¥3,000',
        maxStay: '15-90 days',
      },
    },
    visaTypes: [
      'tourist',
      'business',
      'student',
      'work',
      'transit',
      'working-holiday',
    ],
    requiredDocuments: [
      'Valid passport',
      'Visa application form',
      'Photo',
      'Flight itinerary',
      'Hotel reservations',
      'Financial proof',
      'Purpose of visit documents',
    ],
    embassy: {
      address: '서울특별시 중구 율곡로 64',
      phone: '+82-2-2170-5200',
      website: 'https://www.kr.emb-japan.go.jp',
      workingHours: '09:00-11:30, 13:30-16:00 (Mon-Fri)',
    },
  },

  AU: {
    name: 'Australia',
    region: 'Oceania',
    capital: 'Canberra',
    currency: 'AUD',
    timezone: 'Multiple',
    language: ['English'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
        notes: 'ETA (Electronic Travel Authority) required',
      },
      US: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      JP: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      GB: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      DE: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      FR: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      ES: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      IT: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      CA: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: 'N/A',
      },
      NZ: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      SG: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-2 days',
        fee: 'AUD $20 (ETA)',
        maxStay: '3 months',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '15-20 days',
        fee: 'AUD $145',
        maxStay: '3 months',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '15-20 days',
        fee: 'AUD $145',
        maxStay: '3 months',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '15-20 days',
        fee: 'AUD $145',
        maxStay: '3 months',
      },
    },
    visaTypes: [
      'tourist',
      'business',
      'student',
      'work',
      'transit',
      'working-holiday',
    ],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'ETA application (online)',
      'Health requirements (if applicable)',
      'Character requirements',
      'Sufficient funds proof',
      'Return ticket',
    ],
    embassy: {
      address: '서울특별시 종로구 종로1길 50, 더케이트윈타워 A동 19층',
      phone: '+82-2-2003-0100',
      website: 'https://korea.embassy.gov.au',
      workingHours: '08:30-12:30, 13:30-17:00 (Mon-Fri)',
    },
  },

  // Southeast Asia
  TH: {
    name: 'Thailand',
    region: 'Southeast Asia',
    capital: 'Bangkok',
    currency: 'THB',
    timezone: 'ICT',
    language: ['Thai'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days (by air), 15 days (by land)',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      CN: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'visa-on-arrival',
        processingTime: 'On arrival',
        fee: '$35',
        maxStay: '15 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '3-5 days',
        fee: '$35',
        maxStay: '60 days',
      },
    },
    visaTypes: [
      'tourist',
      'business',
      'student',
      'work',
      'transit',
      'digital-nomad',
    ],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'Return ticket',
      'Proof of accommodation',
      'Sufficient funds (10,000 THB per person)',
      'Visa application form (if required)',
      'Passport photos (if required)',
    ],
    embassy: {
      address: '서울특별시 용산구 이태원로 32길 47',
      phone: '+82-2-795-3098',
      website: 'http://www.thaiembassy.org/seoul',
      workingHours: '09:00-12:00, 14:00-17:00 (Mon-Fri)',
    },
  },

  VN: {
    name: 'Vietnam',
    region: 'Southeast Asia',
    capital: 'Hanoi',
    currency: 'VND',
    timezone: 'ICT',
    language: ['Vietnamese'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '45 days',
      },
      US: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3 days',
        fee: '$25',
        maxStay: '30 days',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '45 days',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '45 days',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '45 days',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '45 days',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '45 days',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '45 days',
      },
      CA: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3 days',
        fee: '$25',
        maxStay: '30 days',
      },
      AU: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3 days',
        fee: '$25',
        maxStay: '30 days',
      },
      NZ: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3 days',
        fee: '$25',
        maxStay: '30 days',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      CN: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3 days',
        fee: '$25',
        maxStay: '30 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '3-5 days',
        fee: '$25',
        maxStay: '30 days',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit'],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'Visa application form',
      'Passport photos',
      'Flight tickets',
      'Hotel bookings',
      'Visa fee payment',
    ],
    embassy: {
      address: '서울특별시 용산구 이태원동 196-4',
      phone: '+82-2-794-1615',
      website: 'https://vnembassy-seoul.mofa.gov.vn',
      workingHours: '09:00-12:00, 14:00-17:00 (Mon-Fri)',
    },
  },

  SG: {
    name: 'Singapore',
    region: 'Southeast Asia',
    capital: 'Singapore',
    currency: 'SGD',
    timezone: 'SGT',
    language: ['English', 'Malay', 'Chinese', 'Tamil'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '90 days',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: 'N/A',
      },
      CN: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '30 days',
      },
      IN: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '1-3 days',
        fee: 'S$30',
        maxStay: '30 days',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '3-5 days',
        fee: 'S$30',
        maxStay: '30 days',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit'],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'Return ticket',
      'Sufficient funds',
      'Yellow fever vaccination (if applicable)',
      'Visa application (if required)',
    ],
    embassy: {
      address: '서울특별시 중구 을지로5길 19, 페럼타워 28층',
      phone: '+82-2-774-2464',
      website: 'https://www.mfa.gov.sg/seoul',
      workingHours: '09:00-12:00, 14:00-17:00 (Mon-Fri)',
    },
  },

  // Other Popular Destinations
  GB: {
    name: 'United Kingdom',
    region: 'Northern Europe',
    capital: 'London',
    currency: 'GBP',
    timezone: 'GMT/BST',
    language: ['English'],
    travelAdvisory: 'low',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      US: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      JP: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      GB: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: 'N/A',
      },
      DE: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      FR: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      ES: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      IT: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      CA: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      AU: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      NZ: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      SG: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: '6 months',
      },
      CN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '15 days',
        fee: '£95',
        maxStay: '6 months',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '15 days',
        fee: '£95',
        maxStay: '6 months',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '15 days',
        fee: '£95',
        maxStay: '6 months',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit'],
    requiredDocuments: [
      'Valid passport',
      'Visa application form',
      'Passport photos',
      'Financial evidence',
      'Accommodation details',
      'Travel itinerary',
      'Tuberculosis test (if applicable)',
    ],
    embassy: {
      address: '서울특별시 중구 세종대로 19길 24',
      phone: '+82-2-3210-5500',
      website: 'https://www.gov.uk/world/south-korea',
      workingHours: '09:00-12:00, 13:00-16:00 (Mon-Fri)',
    },
  },

  CN: {
    name: 'China',
    region: 'East Asia',
    capital: 'Beijing',
    currency: 'CNY',
    timezone: 'CST',
    language: ['Chinese (Mandarin)'],
    travelAdvisory: 'medium',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '¥280',
        maxStay: '30 days (L visa)',
      },
      US: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '$140',
        maxStay: '30 days (L visa)',
      },
      JP: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '¥3,000',
        maxStay: '30 days (L visa)',
      },
      GB: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '£151',
        maxStay: '30 days (L visa)',
      },
      DE: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '€125',
        maxStay: '30 days (L visa)',
      },
      FR: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '€125',
        maxStay: '30 days (L visa)',
      },
      ES: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '€125',
        maxStay: '30 days (L visa)',
      },
      IT: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '€125',
        maxStay: '30 days (L visa)',
      },
      CA: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: 'CAD $140',
        maxStay: '30 days (L visa)',
      },
      AU: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: 'AUD $180',
        maxStay: '30 days (L visa)',
      },
      NZ: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: 'NZD $180',
        maxStay: '30 days (L visa)',
      },
      SG: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: 'S$30',
        maxStay: '30 days (L visa)',
      },
      CN: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: 'N/A',
      },
      IN: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '4-7 days',
        fee: '₹2,000',
        maxStay: '30 days (L visa)',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '7-10 days',
        fee: 'Varies',
        maxStay: '30 days (L visa)',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit'],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'Visa application form',
      'Passport photo',
      'Flight bookings',
      'Hotel reservations',
      'Invitation letter (if applicable)',
      'Financial proof',
    ],
    embassy: {
      address: '서울특별시 중구 명동2가 27-1',
      phone: '+82-2-738-1038',
      website: 'http://kr.china-embassy.org',
      workingHours: '09:00-11:30 (Mon-Fri)',
    },
  },

  IN: {
    name: 'India',
    region: 'South Asia',
    capital: 'New Delhi',
    currency: 'INR',
    timezone: 'IST',
    language: ['Hindi', 'English'],
    travelAdvisory: 'medium',
    popularDestinations: true,
    requirements: {
      KR: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      US: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      JP: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      GB: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      DE: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      FR: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      ES: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      IT: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      CA: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      AU: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      NZ: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      SG: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      CN: {
        visaRequired: true,
        visaType: 'evisa',
        processingTime: '3-5 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
      IN: {
        visaRequired: false,
        visaType: 'visa-free',
        processingTime: 'N/A',
        fee: 'Free',
        maxStay: 'N/A',
      },
      OTHER: {
        visaRequired: true,
        visaType: 'embassy',
        processingTime: '7-10 days',
        fee: '$25-100',
        maxStay: '30-90 days',
      },
    },
    visaTypes: ['tourist', 'business', 'student', 'work', 'transit', 'medical'],
    requiredDocuments: [
      'Valid passport (6+ months validity)',
      'eVisa application (online)',
      'Digital passport photo',
      'Passport scan',
      'Purpose of visit documents',
      'Payment of visa fee',
    ],
    embassy: {
      address: '서울특별시 용산구 한남대로 37',
      phone: '+82-2-798-4257',
      website: 'https://www.eoiseoul.gov.in',
      workingHours: '09:00-13:00, 14:00-17:30 (Mon-Fri)',
    },
  },
};
